package net.somethingdreadful.MAL.tasks;

public enum TaskJob {
    GETLIST,
    GETFRIENDLIST,
    BROWSE,
    FORCESYNC,
    GETMOSTPOPULAR,
    GETMOSTPOPULARS,
    GETMOSTPOPULARY,
    GETTOPRATED,
    GETTOPRATEDS,
    GETTOPRATEDY,
    GETJUSTADDED,
    GETUPCOMING,
    GETDETAILS,
    UPDATE,
    REVIEWS,
    RECOMMENDATION,
    SEARCH
}